CTP-1685 Add unfreeze button to lifecycle block
ucl-isd/moodle-block_lifecycle pull request #13
Opened 2024-01-22 11:18 UTC by nbozhkov-ucl

2024-01-22 12:19 UTC, aydevworks requested changes

2024-01-22 12:19 UTC, aydevworks commented on block_lifecycle.php
> +                if (manager::is_course_frozen($courseid)) {
Minor things:
- It seems make more sense to check if the course is frozen first.
- Could combine the permission check into one line
e.g. `if (has_capability("moodle/site:managecontextlocks", $context)) {`

2024-01-22 12:19 UTC, aydevworks commented on renderer.php
> +        );
Could remove the extra spaces.

2024-01-22 12:19 UTC, aydevworks commented on renderer.php
> +        $context ='';
You overwrote the line (162) above immediately. It made the line 162 useless.

2024-01-22 12:19 UTC, aydevworks commented on renderer.php
> +            '<a href="/admin/lock.php?id=17 . $context" class="btn btn-primary">' .
The context id here is always 17. 😄

2024-01-22 12:25 UTC, aydevworks commented
Also, please check the GHA checks results as well:
e.g. https://github.com/ucl-isd/moodle-block_lifecycle/actions/runs/7610338280/job/20723456253?pr=13

2024-01-22 13:53 UTC, nbozhkov-ucl commented on renderer.php
> +        $context ='';
Meant to be $content = ' ';

2024-01-22 15:25 UTC, nbozhkov-ucl commented
Added changes.

2024-01-22 15:52 UTC, aydevworks commented on renderer.php
> +     *
Line 155: Phpdocs for function block_lifecycle_renderer::show_unfreeze_button has incomplete parameters list (error)

2024-01-22 15:57 UTC, aydevworks commented on renderer.php
> +        $content .= html_writer::div(
could be simplify: 

remove `$content ='';` and `return $content;` then add
```
return html_writer::div(
            '<a href="' . $freezeurl .' " class="btn btn-primary">' . 
            get_string('button:unfreezecoursecontext', 'block_lifecycle') . 
            '</a>'   
        );
```

2024-01-23 10:27 UTC, nbozhkov-ucl commented
Addressed all automatic check issues introduced by my code. Deployed to 43-clc for testing and sign-off.

2024-01-29 06:01 UTC, aspark21 commented on block_lifecycle.php
> +                if (has_capability("moodle/site:managecontextlocks", $context)) {
this doesn't look like the right permission to be using, should be a course level permission not a site level one

2024-01-29 06:04 UTC, aspark21 commented
also - rebase, squash your commits and ignore these failures which aren't related to your change- https://github.com/ucl-isd/moodle-block_lifecycle/pull/14#issuecomment-1914005588

2024-01-30 12:51 UTC, nbozhkov-ucl commented on block_lifecycle.php
> +                if (has_capability("moodle/site:managecontextlocks", $context)) {
Shall I create a new course level capability or maybe reuse existing one -  https://github.com/ucl-isd/moodle-block_lifecycle/blob/main/db/access.php#L43-L51?

2024-01-31 14:46 UTC, nbozhkov-ucl commented on block_lifecycle.php
> +                if (has_capability("moodle/site:managecontextlocks", $context)) {
Seems that unlocking course context always rely on moodle/site:managecontextlocks to unlock course context. Even if I create new capability for the button, user will always need moodle/site:managecontextlock to unfreeze the course context.

2024-02-01 16:01 UTC, nbozhkov-ucl commented on block_lifecycle.php
> +                if (has_capability("moodle/site:managecontextlocks", $context)) {
Currently course admin and tutor roles in Moodle have moodle/site:managecontextlocks set to "Not set". If we want them to be able to unfreeze course context (and use the newly created button in the lifecycle block), we will need to update the permissions for these roles and set moodle/site:managecontextlocks set to "Allow". Hope both last comments gives enough context on the reason for using site level permission. Let me know if you need any further research - I will do it in separate Jira story.

2024-02-01 16:07 UTC, nbozhkov-ucl commented
Rebased, squashed my commits and deployed to 43-clc for review.

2024-02-02 08:51 UTC, aspark21 commented on block_lifecycle.php
> +                if (has_capability("moodle/site:managecontextlocks", $context)) {
we can't be giving everyone a really critical site level permission with site wide effect. This is fundamentally wrong.

If this permission isn't suitable, then we need to create a new one, and if need be this will have to be processed through an ad-hoc task as a way around the the limitations of that permission check. 

@aydevworks may have a second opinion on this.

2024-02-02 08:57 UTC, aspark21 commented on block_lifecycle.php
> +                if (has_capability("moodle/site:managecontextlocks", $context)) {
P.S. at present this MR doesn't meet the definition of done so no, keep CTP-1685 story open, will have to rollover into next sprint, so be it.

2024-02-02 19:20 UTC, aydevworks commented on block_lifecycle.php
> +                if (has_capability("moodle/site:managecontextlocks", $context)) {
By looking at the /admin/lock.php, it looks like it's not very difficult to do the context locking / unlocking.
I think we could try create a new course level permission and do the context unfreezing in our plugin instead of using the /admin/lock.php.

2024-12-14 11:23 UTC, aspark21 commented
Fixed by #17

2024-12-14 11:23 UTC, closed without merging